export const Products = [
  {
    id: 1,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
  {
    id: 2,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
  {
    id: 3,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
  {
    id: 4,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
  {
    id: 5,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
  {
    id: 6,
    path: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/dunk-low-retro-mens-shoes-87q0hf.png",
    name: "Nike Dunk Low Retro",
    category: "Men's shoes",
    quantity: "1 shoes",
    price: "$115",
  },
];
